### ISSUE TITLE
upload_chunked() exception

### ISSUE THREAD

**Issue by Nicolasp38** [ewjoachim/dropbox-python-sdk-py3#1]
Hi,

I am using the following code : 
    uploader = dbc.get_chunked_uploader(f, file_length)
    while uploader.offset < file_length :
        try:
            print(uploader.offset)
            uploader.upload_chunked(chunk_size=1_1024_1024)
        except dropbox.rest.ErrorResponse as e :
            # perform error handling and retry logic
            pass
    uploader.finish(dst_path)

I get an exception :
  File "upload_dir.py", line 44, in upload_file
    uploader.upload_chunked()
  File "/mnt/sdhc-data/dropbox/dropbox/client.py", line 1176, in upload_chunked
    StringIO(self.last_block), next_chunk_size, self.offset, self.upload_id)
TypeError: initial_value must be str or None, not bytes

Nicolas

**Comment by ewjoachim** [comment]
Hi Nicolas,

Since it was released recently, I've mainly been using Dropbox's new [python sdk](https://github.com/dropbox/dropbox-sdk-python) which is python 3 firendly (at least !) and (as far as I know) include the old SDK (this one) so you may want to do that too.

That being said, if the new version don't solve the problem, I'd be happy to help. And even happier if you can provide a pull request.

**Comment by ewjoachim** [comment]
PS : you can see the [improvements](https://github.com/dropbox/dropbox-sdk-python/commits/master/dropbox/client.py) they did to the v1 client and it includes making it py3 compatible, so this repo is now useless...

**Comment by Nicolasp38** [comment]
Bonjour Joachim,

Thanks for the github link. I was not aware of it. On Dropbox site, when downloading Python library, I get another (older ?) one.
The bug is still there but as the associated uploading method is obsolete, the bug is obsolete also ;)

Thanks
Nicolas

**Comment by ewjoachim** [comment]
Yes, their new SDK is in a grey state of "not released yet but we don't know when" so it's not the one you get from the Dropbox website ([except if you know where to look...](https://www.dropbox.com/developers-preview/documentation/python)), and they didn't really give more information on their planning. But still, it has a working testbase (well, [mostly](https://github.com/dropbox/dropbox-sdk-python/pull/19)) and it's the place you want to get your improvements to instead of this fork.

**Comment by Nicolasp38** [comment]
What about mentionning DropBox github repo at the top of README so that visitors are aware of it ?

**Comment by ewjoachim** [comment]
That's what I did yesterday, you should see it and if not, then there's a problem...

**Comment by Nicolasp38** [comment]
Sorry, I did not check.
That's perfect.
